# Generated by Django 5.1.6 on 2025-05-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_solanauser_email_solanauser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solanauser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='solanauser',
            name='username',
        ),
    ]
