# Generated by Django 5.1.6 on 2025-05-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_remove_solanauser_email_remove_solanauser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
